### ISSUE TITLE
Preformance with strung.lua

### ISSUE THREAD

**Issue by Positive07** [pygy/LuLPeg#4]
pygy I really love your projects! hahaha. So have you checked the performance of both working together?

**Comment by pygy** [comment]
Glad you like them :-)

I haven't really tried, because there's little to no overlap.

LuLPeg only uses the `string.gsub` function when evaluating what Roberto calls ["string captures"](http://www.inf.puc-rio.br/~roberto/lpeg/#cap-string) ie things like `pattern / "a string %1"`.

`strung.gsub` was not complete until recently, and its performance is worse than the native methods anyway... What more, the `/ "string"` capture handler creates a closure on the fly, which can't be compiled by LuaJIT, so there's little point trying to avoid the Lua C API-based functions anyway.

**Comment by Positive07** [comment]
Oh I see! I also love your explanations they are really easy to understand thanks!
